# Railway deployment configuration
version: 2

build:
  builder: dockerfile
  dockerfilePath: Dockerfile

deploy:
  healthcheck:
    httpGet:
      path: /health
      port: 8000
  
variables:
  AZURE_OPENAI_API_KEY: ${{AZURE_OPENAI_API_KEY}}
  AZURE_OPENAI_ENDPOINT: ${{AZURE_OPENAI_ENDPOINT}}
  AZURE_OPENAI_DEPLOYMENT_NAME: ${{AZURE_OPENAI_DEPLOYMENT_NAME}}
  AZURE_OPENAI_API_VERSION: ${{AZURE_OPENAI_API_VERSION}}
